### ISSUE TITLE
Implement customer feedback

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/documentation#101]
We just ran through the quickstart guide with a customer and got a few suggestions on what we could improve, I'll just gather them in this ticket instead of opening a new one.

- [ ] Section on distributing the kubeconfig to all nodes should be more prominent
- [ ] Highlight that it is necessary to change localhost in the kubeconfig before distributing
- [ ] Add a note about the kubelet that k3s starts on the orchestrator and that no agent is needed on this node
- [ ] Deploying the CRDs for operators after installation is not mentioned in the quickstart, this should reference `kubectl apply -f /etc/stackable/xxx-operator/crd`

**Comment by lfrancke** [comment]
I assume most of these is irrelevant now, I'll close it for now.
