### ISSUE TITLE
Document how to use configuration overrides in all our operators

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/documentation#104]
We have the operator framework which allows overrides/safety valves but this feature is not documented anywhere.

@maltesander Can probably help with this.

**Comment by stefanigel** [comment]
Document override behaviour for config options

**Comment by fhennig** [comment]
- [ ] druid: https://github.com/stackabletech/druid-operator/pull/154
- [ ] superset: at the moment the config is in the container, so overrides aren't possible

more to be put here

**Comment by siegfriedweber** [comment]
The configuration overrides of Superset are documented in stackabletech/superset-operator#173.

**Comment by siegfriedweber** [comment]
@lfrancke, all linked issues are completed now. This epic can probably be closed.
