### ISSUE TITLE
Getting Started: use discovery ConfigMaps rather than hard-coded ports

### ISSUE THREAD

**Issue by teozkr** [stackabletech/documentation#127]
The getting started guide assumes that each product is available on its "typical" port, which hasn't been true since we stopped using the Stackable agent. As we start making STFU rework releases we should rewrite the docs to use the discovery CMs instead.

Reported at https://stackable-workspace.slack.com/archives/C02ND2BJUJ1/p1642406631020400

**Comment by fhennig** [comment]
I'd like to avoid telling the user to pick infos from a CM, but we're on our way to get the "access services" functionality in stackablectl, which we can then use here.

**Comment by fhennig** [comment]
This has been fixed in the meantime; there are no more hardcoded ports.
