### ISSUE TITLE
Versioned docs

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/documentation#156]
As a user of our software I'd like to be able to read documentation for the version of the platform that I'm running.

Currently we only ever publish the latest version of our documentation.
We do want to publish platform level documentation and later add all versions of all operators. For now we're happy with having the latest platform documentation available.

This is done when..
- [ ] There is a `latest` version of our documentation available that points to the current `main` branches of all our repositories
- [ ] https://docs.stackable.tech points to the latest _released_ version of our platform
- [ ] The documentation site has a way of selecting which version of the documentation to read
- [ ] There are documentation sites available for at least the last released platform version, older versions are optional

**Comment by fhennig** [comment]
At the top of my head, I think this is not super trivial with Antora. Antora supports versions for components, and at the moment we have the "home" component for all platform stuff, and then each operator is a component too. We could easily use the antora version mechanism for the operator versions, but then how do we build the platform version on top?

**Comment by lfrancke** [comment]
Thank you very much. I think all of that makes sense and I have nothing to add.
We can definitely get someone to help you out on the UI part.

**Comment by fhennig** [comment]
This ticket is almost done. Update:
- We now publish documentation for our latest `main` state which is always `nightly` and also published under this name.
- We publish documentation from tags, the format `docs/X.Y` was introduced for these tags.
- We adapted the Makefile in operator-templating to automatically derive the antora component version from the cargo package version
- A dropdown to select a version shows up in the UI (top right) if multiple versions are present
- There is a `stable` link which always links to the latest stable version.

What's left to do:
- release a stable docs version for every component
- Adapt the menu links for all operators to point to the stable version (currently points to nightly)
