### ISSUE TITLE
Include all our products in the Getting Started guide

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/documentation#160]
As a user of the platform I'd like to have one simple tutorial to follow to install the whole platform and have all tools from the platform running.

I want our documentation to follow this practice: https://diataxis.fr/
This basically means all documentation must fall in one of these categories: Tutorial, How-to guide, Reference, Explanation.
This ticket is about a [Tutorial](https://diataxis.fr/tutorials/).

This is done when a user
- [ ] can read a tutorial (it may be split over multiple pages but it should be a clear path "Next page" through the whole tutorial) with step-by-step directions on how to install every operator in our platform
- [ ] and each operator section is accompanied with an example on how to deploy its product, this example can be minimal
- [ ] and the written documentation follows the rough guidelines from this site: https://diataxis.fr/tutorials/

Edit TODO: Convert to Epic

**Comment by fhennig** [comment]
I'm not sure if this is useful, unless all the tools somehow interact with each other. I'd rather have a few different tutorials that cover certain groups of products. I'd imagine there's a hadoop cluster of products, and then there's stuff aroud trino. And I also imagine every potential user has their preferred stack of products that they are interested in.

So I'd rather have ~3 different getting started "tracks", depending on your preferred stack.

**Comment by lfrancke** [comment]
Thanks for bringing this up again!
Honestly: I'm  fine with the Getting started guides as they are now.
If you like we can do as you suggested and include all of them in one big list. I'd also be fine with closing this ticket.

What do you prefer?

**Comment by fhennig** [comment]
I'd like to move the tutorial-style part of the guide into a tutorial, I'd like to keep the part about installing k8s and move it into a dedicated page to link to from other places, and then I'd like to have a list of all the getting started guides for the products. Then we could direct the user to the appropriate places: getting started with a product, or with a sample use-case tutorial. (sorry for replying so late)

**Comment by fhennig** [comment]
okay, here is the list of all getting started guides: https://docs.stackable.tech/home/nightly/tutorials/
and here is the page about k8s getting started: https://docs.stackable.tech/home/nightly/kubernetes#local-installation

I consider this done now.
