### ISSUE TITLE
Add documentation on concepts: Roles and Role Groups

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/documentation#191]
We don't currently have documentation on the terms _role_ and _roleGroup_.

We should add a glossary or concepts section that explains these.

**Comment by fhennig** [comment]
This is an [explanation](https://diataxis.fr/explanation/) topic, we have those in the Concepts section. I used ADRs as a base for page like this, but I don't think we have one for role and roleGroup. I haven't used this feature much, it'd be good to gather some infos on it, what should go into a concept page explaining this (why was this added and why in this way)
