### ISSUE TITLE
Support tab blocks

### ISSUE THREAD

**Issue by fhennig** [stackabletech/documentation#208]
I'd really like to have tabbed blocks available, for example to have install steps for linux/mac as two tabs to take up less space.

There's this extension from couchbase we could try and integrate: https://github.com/couchbase/docs-site/blob/9896e4500fa2012ca8da00d9036f5d0f1d23cdb2/lib/tabs-block.js

There's also a more "official" extension: https://gitlab.com/antora/antora-asciidoctor-extensions/-/blob/main/tabs-block/extension.js that might work

For example [here](https://docs.couchbase.com/server/current/install/ubuntu-debian-install.html) is such a block, with "Enterprise" and "Community" tabs.

**Comment by NickLarsenNZ** [comment]
Another example (for variety): https://docs.dapr.io/getting-started/quickstarts/pubsub-quickstart/

**Comment by fhennig** [comment]
Another example, even more involved: https://docs.cloudera.com/cdp-private-cloud-upgrade/latest/upgrade-cdp/topics/ug_cm_upgrade_before-cdp.html

In here you have multiple drop downs to select 'your environment' which is used throughout the article
