### ISSUE TITLE
Callouts don't work with highlightjs

### ISSUE THREAD

**Issue by fhennig** [stackabletech/documentation#232]
A [Callout](https://docs.asciidoctor.org/asciidoc/latest/verbatim/callouts/) is the little number in a circle to annotate source code listings. I've noticed that these don't work on source blocks with highlighting enabled, sadly. It seems like highlightjs is breaking them. I'm unsure what a fix could be.

Here's an example of what it looks like broken: https://docs.stackable.tech/druid/stable/usage.html#_s3_deep_storage

**Comment by teozkr** [comment]
This seems to be related to our custom UI bundle, switching back to Antora's default bundle seems to "fix" it.

**Comment by fhennig** [comment]
A bit of research results: 
- The breaking commit seems to be this one: https://github.com/stackabletech/documentation-ui/commit/d5c3d38c7ee9348ddb01ee552995384e5c8a781c Highlight.js was upgraded here, from v10 to v11 with some breaking changes.
- Callouts work in code blocks without highlighting, i.e. if only `[source]` instead of i.e. `[source,yaml]` is used.
- The default Antora UI has not yet upgraded to highlightjs 11, they are still at v9.

It seems to be that the new highlightjs is breaking the callouts.

**Comment by fhennig** [comment]
We decided to downgrade to v10 and look at this again when Antora upgrades highlightjs in the Default UI

**Comment by fhennig** [comment]
Hey, thanks for raising the issue there. I'm interested in seeing how it'll go!
