### ISSUE TITLE
Upgrade documentation 2022-06 -> 2022-09

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/documentation#233]
Needs to be done by the time of the release
Copied from https://github.com/stackabletech/.github-private/blob/main/profile/README.md:

- [x] Document how to use stackablectl to uninstall all and install new release
- [x] Document how to use helm to uninstall all and install new release
- [x] Every breaking change of all our operators
- [x] List dropped supported product versions (if there are some)
- [x] List dropped supported operators (if there are some)
- [x] List supported k8s versions

**Comment by adwk67** [comment]
> Putting this on track as I'd like to wait with merging for the actual release

_Originally posted by @sbernauer in https://github.com/stackabletech/documentation/issues/268#issuecomment-1236906140_

**Comment by lfrancke** [comment]
We need to make sure that https://github.com/stackabletech/trino-operator/pull/278 is covered (I haven't looked at the PR, it might already be)

**Comment by sbernauer** [comment]
Docs are adopted to to reflect trino-op 0.6.0 :heavy_check_mark:
