### ISSUE TITLE
Wrong Helm repository name

### ISSUE THREAD

**Issue by razvan** [stackabletech/documentation#246]
Hi

Thanks again Razvan.

I noticed that there are pages with different repo names when using helm. For instance:
- https://docs.stackable.tech/home/getting_started.html:
> helm repo add stackable-stable https://repo.stackable.tech/repository/helm-stable/
- https://docs.stackable.tech/druid/stable/installation.html
> $ helm repo add stackable https://repo.stackable.tech/repository/helm-stable/

As you can see, the name is different leading to the following error when you try to install something: Error: INSTALLATION FAILED: failed to download "stackable/druid-operator"

**Comment by lfrancke** [comment]
This has been mostly fixed already by the looks of it.

I only found references in the release notes to a repo called "stackable" and I'll submit a PR
