### ISSUE TITLE
Update quickstart guide with stackablectl

### ISSUE THREAD

**Issue by siegfriedweber** [stackabletech/documentation#249]
The [quickstart guide](https://docs.stackable.tech/home/quickstart.html) shows how to setup a Stackable cluster with the `create_test_cluster.py` script. When stackabletech/stackablectl#36 is finished then it should be changed to use `stackablectl`.

**Comment by fhennig** [comment]
The "example" doesn't really exist anymore, i've talked to Sebastian and he suggested to use the `trino-taxi-data` demo in the quickstart.
