### ISSUE TITLE
Documentation: System requirements platform components

### ISSUE THREAD

**Issue by stefanigel** [stackabletech/documentation#258]
As part of General Availability it is necessary to document system requirements to run SDP or parts of SDP as part of our documentation.
We start with documenting the setup we are using for our tests as a first increment.
This description from Cloudera may serve as an example:
[https://docs.cloudera.com/documentation/enterprise/6/release-notes/topics/rg_hardware_requirements.html#concept_fzz_dq4_gbb]

**Acceptance criteria:**
- [ ] the described configurations describe setups where we our tests are running 
- [ ] the documentation is versioned and refers to an actual release (starting from 22-06)
- [ ] the documentation can be referenced from our GTCs and other contract documents
- [ ] Stackable support team is willing to accept incoming support issues that run on the described configuration
- [ ] the configuration describes supported versions of Operating System (at least for stackablectl), Kubernetes product and version (managed and on-prem products), data platform component versions

**Comment by stefanigel** [comment]
Seems to be a duplicate to: #247

**Comment by lfrancke** [comment]
I believe this is now covered as part of #247
