### ISSUE TITLE
Documentation: Which K8S Products and Versions do we support?

### ISSUE THREAD

**Issue by stefanigel** [stackabletech/documentation#261]
As an operator of SDP I want to know which K8S products are supported in which versions because I want to choose a working ´ setup for my data platform.

TODO:
- revisit and rework [ADR 13: Supported Kubernetes versions](https://docs.stackable.tech/home/stable/contributor/adr/ADR013-supported_kubernetes_versions.html)
- identify other 2nd tier dependencies, e.g. has k8s to run on a specific OS with specific libraries / packages installed? 
- something special to consider for managed K8S?
 
Acceptance criteria:
- [x] list of supported K8S products and versions
- [x] list is part of the Stackable documentation 
- [ ] list of any other known aspects/linimtations/boundary conditions of each k8s product
- [x] list can be referenced as an URL from support subscription contracts, probably versioning / archiving required maybe related to a release?
- [x] there is a consent that a precondition to accept SDP support tickets is met if a customer runs SDP on one of the listed products/versions

**Comment by fhennig** [comment]
There's a related ticket: https://github.com/stackabletech/documentation/issues/205 about writing a page about how to set up a k8s cluster. Maybe those can be somehow be tied together

**Comment by fhennig** [comment]
@stefanigel there is this document now: https://docs.stackable.tech/home/nightly/kubernetes

Do you think that is sufficient to close this ticket? In the ticket you still have these open questions:

identify other 2nd tier dependencies, e.g. has k8s to run on a specific OS with specific libraries / packages installed?
something special to consider for managed K8S?

But they are quite open ended. I can't think of any additional special requirements

**Comment by fhennig** [comment]
I'll close this, there is a similar ticket coming up: https://github.com/stackabletech/issues/issues/450
