### ISSUE TITLE
document resource limits

### ISSUE THREAD

**Issue by fhennig** [stackabletech/documentation#263]
There is a common [resource](https://github.com/stackabletech/operator-rs/blob/main/src/commons/resources.rs) in the operator-rs to configure pod resource settings. We want to have some documentation for the resources concept that can be linked from the operators. It should be similar to this page: https://docs.stackable.tech/home/stable/concepts/s3.html.

## Blocking / Open questions
- Operators use different names and amounts of PVCs. How do we want to handle this via a general concepts page? 
- Java product-based Operators e.g. calculate down the heap memory (currently 0.8 * pod memory) that will be set for the process. How do we specify this per operator (not required for python based ones)? 

## Acceptance

- [x] A new concepts page for resources is included in the documentation 
- [x] This page shows the usage of allocating PVCs (with a hint that this must adhere to the PVCs required by the operator)
- [x] This page shows the utilization of memory and CPU settings
- [x] Optional: The relationship of pod memory and e.g. Java heap is described (not sure this belongs in a general concepts page)
- [x] This page is referenced by all operators using these resources (please add the Issues/PRs here)

### Products
- [x] Airflow https://github.com/stackabletech/airflow-operator/pull/172
- [x] Druid https://github.com/stackabletech/druid-operator/pull/308
- [x] HBase https://github.com/stackabletech/hbase-operator/pull/256
- [x] Hadoop HDFS https://github.com/stackabletech/hdfs-operator/pull/244
- [x] Hive https://github.com/stackabletech/hive-operator/pull/249
- [x] Kafka https://github.com/stackabletech/kafka-operator/pull/485
- [x] NiFi https://github.com/stackabletech/nifi-operator/pull/353
- [x] Spark https://github.com/stackabletech/spark-k8s-operator/pull/147
- [x] Superset https://github.com/stackabletech/superset-operator/pull/279
- [x] Trino https://github.com/stackabletech/trino-operator/pull/301
- [x] ZooKeeper https://github.com/stackabletech/zookeeper-operator/pull/563
- [x] OPA https://github.com/stackabletech/opa-operator/pull/352

**Comment by razvan** [comment]
Bugfix for link to roles concept: https://github.com/stackabletech/documentation/pull/293
