### ISSUE TITLE
Create ADR on CRD versioning

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/documentation#273]
We do not currently version our CRDs in a proper fashion, but rather just yolo changes. 

This is something that we urgently need to change and introduce proper versions for all our CRDs. However I believe that this requires us to provide conversion functions and controllers to run these functions, which makes this a somewhat larger issue than just updating the version in our CRDs.

This ticket is done when:
- [ ] An ADR was written and accepted that details what needs to be done and outlines the options
- [ ] An option was chosen
- [ ] Appropriate follow up tickets for the chosen option have been created

**Comment by teozkr** [comment]
Yes, we need this. No, this doesn't have anything whatsoever to do with how Helm deploys the CRDs. To quote [the docs](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations):

> There is no support at this time for upgrading or deleting CRDs using Helm.

**Comment by soenkeliebau** [comment]
> There is no support at this time for upgrading or deleting CRDs using Helm.

Fuck

**Comment by fhennig** [comment]
There is now an epic: https://github.com/stackabletech/issues/issues/507

I'm closing this in favor of the epic (which also links to a different ADR ticket)
