### ISSUE TITLE
Search returns broken links

### ISSUE THREAD

**Issue by timrobertson100** [stackabletech/documentation#279]
~~A search for “Hive” on https://docs.stackable.tech/home/stable/index.html the first entry isn’t clickable.~~ Clicking the link going to the main page doesn't jump to the correct section on the page.

<img width="689" alt="Screenshot 2022-09-13 at 11 36 24" src="https://user-images.githubusercontent.com/237221/189867464-f312ab2e-e6a8-4477-8bd8-eff5a1424cd2.png">

## Expected behaviour

Either a jump to the [`_components` anchor](https://docs.stackable.tech/home/stable/index.html#_components) or to a specific "Hive" anchor on the page

## Acceptance criteria

- [ ] This is fixed when the search causes the jump to the section as described above
- [ ] Change should be applied to all releases

**Comment by fhennig** [comment]
Hi!

This is a tricky one. It actually is clickable, but it is linking to the page you're currently on (the landing page). If you search while being on a different page, it will bring you to the landingpage.

**Comment by timrobertson100** [comment]
Ah yes, I see. I just didn't scroll down far enough to notice that the Hive docs are linked from that page.
Suggest to just close this issue.

**Comment by fhennig** [comment]
Yes, an anchor would be good, as there will be others confused by this. I'll leave this ticket open

**Comment by fhennig** [comment]
The sub heading on the main page is made with an HTML tag:
    
    ++++
    <h3>Apache Hive</h3>
    ++++
    
    The Apache Hive data warehouse software facilitates reading, writing, and managing large datasets residing in distributed storage using SQL. We support the Hive Metastore.
    
    xref:hive::index.adoc[Read more]

I think this is why there is no anchor? If we click the search, we jump to an anchor `undefined`. I suspect that setting an anchor on the heading might solve the problem.

**Comment by fhennig** [comment]
This is a bug, so I don't think there is more refinement to be done. I've updated the issue description with expected behavior and an acceptance criterium

**Comment by fhennig** [comment]
Commits cherry picked to:
- https://github.com/stackabletech/documentation/tree/release/22.06
- https://github.com/stackabletech/documentation/tree/release/22.09
