### ISSUE TITLE
Investigate OpenSSL vs RusTLS

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/documentation#29]
While rolling out the demo environment we noticed that there was an issue with executing binaries that were compiled on a different linux version - most probably due to dynamically linked openssl libraries.
RustTLS might be an alternative that allows to build statically linked binaries, this is worth a look to see if the switch might improve things.

**Comment by lfrancke** [comment]
@soenkeliebau I assume most of this'd become irrelevant when moving to containers?

**Comment by lfrancke** [comment]
Closing for now because I don't think there's much for us to do at the moment.
We might switch to RusTLS at some point but not now.
Happy to reopen as soon as we have a good reason to do so.
