### ISSUE TITLE
Make the LDAP documentations self-contained

### ISSUE THREAD

**Issue by siegfriedweber** [stackabletech/documentation#300]
## Problem description

Some operators support authentication via LDAP.  LDAP documentation in the operators is not consistent across operators, and not self contained. Some documentation links to the integration tests for details, in other places hypothetical values are used.

Inconsistencies (or even missing steps) make it harder for the user to get a working setup.

<details>
<summary>Click here for details</summary>

The operator documentations only contain the cluster specification which shows how to connect to an existing LDAP server. It is not described how to set up LDAP which matches the shown cluster specification. The documentation is not self-contained and cannot be tried out.

The documentation of the Airflow operator points to an example in the operator repository which uses the OpenLDAP image from Bitnami to create an LDAP instance with two users. The example works well but is not included in the documentation.

The documentations of the NiFi and Trino operators just point to their integration tests. The tests contain KUTTL assertions, Jinja templates, Shell and Python scripts. They are impractical for documentation purposes.

The documentation of the Commons operator just uses hypothetical configuration values.
</details>

### Operators with LDAP support
- Airflow
- NiFi
- Trino
- Superset
- Druid (WIP)

### Relevant docs pages
- [concepts > AuthenticationClass](https://docs.stackable.tech/home/nightly/concepts/authenticationclass.html)
- [Airflow > usage > LDAP sections](https://docs.stackable.tech/airflow/nightly/usage.html#_ldap)
- [NiFi > usage > LDAP sections](https://docs.stackable.tech/nifi/nightly/usage.html#_ldap)
- [Trino > usage > Security > LDAP section](https://docs.stackable.tech/trino/stable/usage_guide/security.html#_ldap)
- [Superset > usage > LDAP sections](https://docs.stackable.tech/superset/nightly/usage.html#_ldap_2)

### How LDAP in Stackable actually works

- configure an AuthenticationClass with an `ldap` provider
- reference this AuthenticationClass instance in the ProductCluster definition

Typically LDAP would already be installed. We do not have an LDAP operator, the User needs to provide their own LDAP. What if the LDAP is running outside of the cluster?

To get something running, an LDAP instance is necessary. We don't support LDAP as a product, but maybe we can have a tutorial to set something up that is explicitly not production ready? Maybe a stack?

## Solution

- [x] Create a **Stack** for OpenLDAP in stackablectl to be used in the Tutorial: https://github.com/stackabletech/stackablectl/pull/195
- [x] Create a **Tutorial** how to set up OpenLDAP and connect a couple of products: https://github.com/stackabletech/documentation/pull/334
- [ ] ~~Create a **Guide** giving instructions on how to connect an LDAP running outside of the cluster, and then use it in the products~~
- [x] Refactor the `AuthenticationClass` concept page to be less instructional and more conceptional and make it link to the tutorial and guide. https://github.com/stackabletech/documentation/pull/339
- [x] Link these pages in all Operators that use LDAP.
    - [x] Airflow https://github.com/stackabletech/airflow-operator/pull/215
    - [x] NiFi https://github.com/stackabletech/nifi-operator/pull/406
    - [x] Trino https://github.com/stackabletech/trino-operator/pull/365
    - [x] Superset https://github.com/stackabletech/superset-operator/pull/310
    - Druid: Will be done in the LDAP implementation PR: https://github.com/stackabletech/druid-operator/pull/374

**Comment by fhennig** [comment]
I think I like a general tutorial, and operator specific things in dedicated LDAP pages in the operators.

**Comment by fhennig** [comment]
The LDAP structs: https://github.com/stackabletech/operator-rs/blob/main/src/commons/ldap.rs

**Comment by fhennig** [comment]
I found a couple of bugs: https://github.com/stackabletech/issues/issues/322 they impact the tutorial, but I think I can work around it

**Comment by fhennig** [comment]
update: There is now this reorg PR https://github.com/stackabletech/documentation/pull/339

After that is merged, I'll link to all the new pages from the operators and clean up LDAP docs in there

**Comment by lfrancke** [comment]
Can this be closed?

**Comment by fhennig** [comment]
Yes
