### ISSUE TITLE
Test a workaround to not mark a redirect page as noindex

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/documentation#324]
Antora automatically adds a `noindex` to redirect pages it creates automatically.
@stackfab has a theory that this might lead to our docs not being indexed by Google (one data point: Bing successfully indexed all of it).

As this is hardcoded and I want to avoid running a patched version of Antora one thing we _could_ try is some hack in Github Actions workflow after the build but before the deploy to change the generated page to remove the offending line.

See this discussion: https://antora.zulipchat.com/#narrow/stream/282400-users/topic/site.20start_page.20and.20noindex.20meta.20tag
The site in question is https://docs.stackable.tech (NOT the site it redirects to! which would be https://docs.stackable.tech/home/stable/index.html )

**Comment by fhennig** [comment]
The fix is live, but we don't know yet if it worked. 
We can close this ticket once we know one way or the other

**Comment by fhennig** [comment]
Update: The site is still not crawled, the change needs to be undone.
