### ISSUE TITLE
The version dropdown in the documentation is fairly inconspicuous

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/documentation#368]
Just ran into this with a customer when installing the SDP, the version link in our documentation is fairly small and scrolls out of the screen when going down on the page.
Also, the left menu gets hidden for smaller windows, which makes the link disappear completely.

In our case this actually caused stuff to break because we were looking at an incompatible example.

Maybe we can make the version of the docs more "obvious" somehow?

**Comment by fhennig** [comment]
Sounds like a good idea
