### ISSUE TITLE
Create section in the docs that explain shared structs in operator CRDs

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/documentation#370]
We are working towards introducting a global shared structure in all our CRDs, for example:
- clusterConfig
- rolegroups
- rolegroupconfig
- logging 
- ...

For all the stuff that is global we should have a section in the docs that shows this shared structure and explains at a high level what goes where.

**Comment by fhennig** [comment]
most things that exist across operators already have a concepts page https://docs.stackable.tech/home/stable/concepts/index.html (i.e. roles and role groups, logging).

I have sketched out before an overarching page that brings all of these together. I like your idea!

**Comment by fhennig** [comment]
I am closing this, feel free to reopen this @soenkeliebau if you think something is still missing.
