### ISSUE TITLE
Getting Started for HDFS (possibly others) refers to patch level versions

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/documentation#419]
https://docs.stackable.tech/home/stable/hdfs/getting_started/installation.html says

```
stackablectl operator install \
  commons=23.4.0 \
  secret=23.4.0 \
  zookeeper=23.4.0 \
  hdfs=23.4.0
```

Which (at the time of this writing) was not the latest version, it was 23.4.1, the docs should just refer to `23.4` instead

**Comment by adwk67** [comment]
This has been addressed in the release script [here](https://github.com/stackabletech/stackable-utils/commit/a7fde93de64ad07d8307c87a6c1b56d99b2dc48e).

**Comment by adwk67** [comment]
Yes, this can be closed.

**Comment by lfrancke** [comment]
That's fabulous. Thanks!
