### ISSUE TITLE
Awkward search result versioning order

### ISSUE THREAD

**Issue by nightkr** [stackabletech/documentation#444]
When currently making a search for `k8ss`, I get the following results:

![image](https://github.com/stackabletech/documentation/assets/649832/81e3ca8b-02b8-4155-bed3-e5cda0f1b10a)

This directs the user to the *nightly* version as the first option, and shows several old versions above the current release (23.7, at the time of writing).

**Comment by fhennig** [comment]
Hmm, the extension we use has very little config options, but I looked again. What we could do is only index the latest stable. What do you think about that as a fix?

https://gitlab.com/antora/antora-lunr-extension#user-content-configuration

**Comment by fhennig** [comment]
The new search only searches in the latest stable version, so this is fixed now.
