### ISSUE TITLE
Release branch script

### ISSUE THREAD

**Issue by fhennig** [stackabletech/documentation#510]
There is a `version_bump.sh` script, but it is outdated. Create a script that gets given a release (with full major.minor.patch) and then

- check if on main branch, working directory empty and up-to-date
- checkout new branch "release/major.minor"
- update antora.yaml file:
    - set the 'version' key
    - set the 'prerelease' key to false
    - set the 'crd-docs-version' key
- show a diff and ask for confirmation
- commit changes
- push the branch

This does  the checks (probably):

```bash
#!/bin/bash

# Check if on main branch
current_branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$current_branch" != "main" ]; then
    echo "Not on the main branch. Please switch to the main branch."
    exit 1
fi

# Check if the branch is up to date with the origin
git fetch
if [ "$(git rev-parse HEAD)" != "$(git rev-parse origin/main)" ]; then
    echo "Your branch is not up to date with the origin main branch. Please pull the latest changes."
    exit 1
fi

# Check if the working directory is clean
if [ -n "$(git status --porcelain)" ]; then
    echo "Working directory is not clean. Please commit or stash your changes."
    exit 1
fi

echo "All checks passed. You are on the main branch, up to date with the origin, and the working directory is clean."


```

**Comment by adwk67** [comment]
Should this script reside in stackable-utils? If not we should at least mention it in the README there so that we have release-related info in one place.

**Comment by fhennig** [comment]
Ah yeah so I was thinking about keeping the script in the docs repo, but definitely link it from stackable-utils. But since the procedures in it are specific to the docs repo I thought it makes sense to maintain it in here. What do you think?

**Comment by adwk67** [comment]
Yes, that makes sense. As long as we link it so that it is clear that it is part of the release process steps.
