### ISSUE TITLE
Document Cargo.toml formatting

### ISSUE THREAD

**Issue by NickLarsenNZ** [stackabletech/documentation#528]
It is good to have consistent formatting for consistency between developers (eg: using rustfmt for ust code) to reduce noise around style in PR reviews.

Automatic formatting is a preference, however exising TOML formatters (as far as we know) apply rules across the whole toml file (and not only Cargo.toml), rather than different rules per section or use case of toml.

For example,
- we would like `[dependencies]` to be ordered alphabetically
- we would like important `[project]` attributes to be at the top of the section

So, for now we should document how we expect Cargo.toml to look, to avoid it repeatedly coming up in PRs.

**Comment by NickLarsenNZ** [comment]
I found some kind of style guide (for reference): https://github.com/rust-lang/rust/blob/master/src/doc/style-guide/src/cargo.md

**Comment by sbernauer** [comment]
I think we can throw a link to https://github.com/rust-lang/rust/blob/master/src/doc/style-guide/src/cargo.md in our guidelines and call it a day until we got rustfmt support, WDYT?

**Comment by sbernauer** [comment]
FYI, just saw https://github.com/apache/iceberg-rust/pull/167

**Comment by fhennig** [comment]
I'm working on this now: https://github.com/stackabletech/documentation/pull/535

@sbernauer taplo looks interesting but I think we can just wait until it'll be native in rustfmt, not worth the effort to add another tool to our build process. If you think it's worth investigating maybe track it in a new issue.

**Comment by sbernauer** [comment]
> but I think we can just wait until it'll be native in rustfmt, not worth the effort to add another tool to our build process

100% agreed
