### ISSUE TITLE
NiFi and Hive Getting Started guides need to be updated

### ISSUE THREAD

**Issue by Jimvin** [stackabletech/documentation#549]
The getting started guide references use of `stackablectl` with the removed `svc` option.

https://docs.stackable.tech/home/stable/nifi/getting_started/first_steps

The docs should be updated to use the correct command line options. We should also check to ensure the guide works with the latest versions of Stackable.
```[tasklist]
### Tasks
- [ ] Fix NiFi getting started guide
- [ ] Hive: https://docs.stackable.tech/home/nightly/hive/getting_started/installation
```

**Comment by NickLarsenNZ** [comment]
I will take a look. I have the latest version of stackablectl (built from main).

**Comment by razvan** [comment]
Closing because the guides have been checked here: https://github.com/stackabletech/issues/issues/539
