### ISSUE TITLE
Mention TLS server verification in AuthClass OIDC docs

### ISSUE THREAD

**Issue by sbernauer** [stackabletech/documentation#654]
Raised in https://github.com/stackabletech/superset-operator/issues/534

Document `tls` property for an OIDC AuthClass in https://docs.stackable.tech/home/nightly/concepts/authentication#OIDC, ideally linking to https://docs.stackable.tech/home/nightly/concepts/tls-server-verification

**Comment by NickLarsenNZ** [comment]
Just adding some relevant conversation from a while back when we were discussing splitting hostname and port, vs making it a url (where tls can be implied from): https://github.com/stackabletech/documentation/pull/460#discussion_r1406414427
