### ISSUE TITLE
Decide about our logging strategy for our own code and write ADR if needed

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/documentation#68]
Decide on and (if necessary) document how we want do logging and tracing in our operators.

A few _ideas_ that came up:

* Using structured logs (JSON) + human readable output
  * The goal should be that our operators (this is not about the services we manage) do emit logs in a human readable as well as in a machine readable format if at all possible.
* Add an "Announcer" component that emits logs to stdout, emits a Kubernetes event, sets a special field in the status of the object (e.g. "status" or "lastMessage"), this concept stems from the Clickhouse Operator
* Do all preparation work to automatically ingest/parse logs into an OpenSearch (or similar) index
* Tracing (e.g. Jaeger/OpenTracing support)
* Every `error` message could have a unique code that can be looked up on our documentation site for more information

Add your own ideas/goals here...

See these links for some information:

* https://github.com/clux/kube-rs/issues/457
* https://github.com/tikv/rust-prometheus/pull/395
* https://discord.com/channels/500028886025895936/685161813675212899/818949608755429377
* https://github.com/clux/controller-rs/blob/b99ad0bfbf4ae75f03323bff2796572d4257bd96/src/telemetry.rs#L4-L8
* https://github.com/clux/controller-rs/blob/b99ad0bfbf4ae75f03323bff2796572d4257bd96/src/manager.rs#L44-L46

In general: As a user of our operators I want to be able to gain as much insight into the inner workings of the operators as possible: Which decisions have been taken and why, which errors did occure etc.

This ticket serves as a research task for someone (or a team) to look at what's out there, which ideas make sense, which don't etc. and then to prepare a decision that can be decided upon in our architecture meeting.

**Comment by fhennig** [comment]
Initial Jaeger support has been implemented already, but in the operators tracing is not ready yet. We don't have an ADR (I think it would be good to have one).

The Announcer idea also seems nice, we already to propagate errors into the events (but not logging in general).

**Comment by fhennig** [comment]
I'm closing this ticket, as it is out of place in this repo and I made a new ticket here: https://github.com/stackabletech/issues/issues/242
