### ISSUE TITLE
Document deploying Stackable services on standard K8s

### ISSUE THREAD

**Issue by Jimvin** [stackabletech/documentation#76]
We need to redo the Getting Started guide to work against the new Kubernetes-native architecture.
For now it is fine if we _only_ mention a K3s based installation.

I'd like this new documentation to include "Getting started" sections/examples on how to deploy each of our services (i.e. example YAML files).

I also want a section on how to deploy everything locally using kind (and possibly Helm but if we can do without Helm I'd be happy too).

**Comment by lfrancke** [comment]
We require an apiserver but those come in multiple flavors

    K3s
    K0s
    kind
    minikube?
    kube-apiserver
    ....

We need some documentation on at least one of those options for customers who don't have an existing Kubernetes cluster.
And we also need documentation on how to configure an existing cluster to work with us.
There might be requirements around Service Accounts etc.

**Comment by lfrancke** [comment]
I'd like this new documentation to include "Getting started" sections/examples on how to deploy each of our services (i.e. example YAML files). 

I also want a section on how to deploy everything locally using kind (and possibly Helm but if we can do without Helm I'd be happy too)

**Comment by lfrancke** [comment]
I decided to close this ticket in favor of a new one to extend the Getting Started guide
