### ISSUE TITLE
Documentation Site Theming

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/documentation#82]
Currently we use the default template for our documentation site.
We need to theme it a bit to look like Stackable and we also need to make the entry point and menu structure nicer.
The drop-up menu at the bottom left to switch between operatos is not nice to use.

The Couchbase docs (https://docs.couchbase.com/home/index.html) are made using Antora and can serve as a nice example.

We probably need some external design help for this.

**Comment by soenkeliebau** [comment]
Can we move this back to "ready for work" for now @lfrancke ?
