### ISSUE TITLE
Publish blog post/use-case article on Trino

### ISSUE THREAD

**Issue by berndfo** [stackabletech/documentation#87]
@Jimvin has written an article on how to get started with Trino in our internal Wiki (https://stackable.atlassian.net/wiki/spaces/STACKABLE/pages/815398913/Getting+Started+With+Trino)

This is worth publishing on our blog post. 
I'm not sure if we also want to add it to our documentation somewhere? Opinions welcome.

This should only be published when our platform is running on K8s proper.

Acceptance Criteria

- [ ] Article is published as a blog post

**Comment by soenkeliebau** [comment]
Looks good to me, I left a few nit-comments, but nothing major.

The only thing I can think of is to add a final paragraph that just provides a bit of "and this wraps up what we wanted to do today, as we have seen, Trino allows us to easily yada yada".

**Comment by lfrancke** [comment]
We decided to split this issue into two parts.
This is more a tutorial/how-to guide which might get published as a blog post.
There was some confusion around this.

I'll add another (more important) ticket for now to add all missing products to the Getting Started guide section of the documentation

**Comment by razvan** [comment]
Can we close this issue ? We now have better docs and demos.

**Comment by lfrancke** [comment]
Yes, thank you!
